project_id = "anbbntvecpjxeeshmtwk"

[functions.ai-mentor]
verify_jwt = true

[functions.career-suggestions]
verify_jwt = true

[functions.course-suggestions]
verify_jwt = true

[functions.execute-code]
verify_jwt = true
